name: 0
uuid: ''
tutorial: {}

oscillate: 'off' # placeholder for automated _oscillate settings

audio_thickness: 0
audio_usewaveform: false

camera_mode: manual
camera_mode_volume: 1.0
camera_mode_volume_oscillate: 'off'
camera_rotationx_oscillate: 'off'
camera_rotationy_oscillate: 'off'
camera_rotationz_oscillate: 'off'
camera_rotationx: 0
camera_rotationy: 0
camera_rotationz: 0
camera_x: 0
camera_x_oscillate: 'off'
camera_y: 0
camera_y_oscillate: 'off'
camera_z:  1
camera_z_oscillate: 'off'

coloring_mode: 'off'
coloring_volume: 1.0
coloring_volume_oscillate: 'off'
coloring_hue: 0
coloring_sat: 1
coloring_lum: .5
coloring_hue_oscillate: 'off'
coloring_sat_oscillate: 'off'
coloring_lum_oscillate: 'off'
coloring_opacity: 1.0
coloring_opacity_oscillate: 'off'
coloring_audio: false
coloring_limit: false
coloring_sync: true
coloring_emissive: true

filter_mode: 'off'
filter_audio: false
filter_limit: false
filter_sync: false
filter_volume: 1.0
filter_volume_oscillate: 'off'

mesh_material: 'lambert'
material_blending: NormalBlending
material_blendequation: AddEquation
material_blendsrc: SrcAlphaFactor
material_blenddst: OneMinusSrcAlphaFactor
material_mapping: 'default'
material_shininess: 2
material_roughness: 0.5
material_metalness: 0.5
material_side: 2
material_softshading: false
material_shadowside: 2
material_map: 'none'
material_input: 'texture'
material_style: fill
material_wraps: ClampToEdgeWrapping
material_wrapt: ClampToEdgeWrapping
material_repeatx: 1.0
material_repeaty: 1.0
material_offsetx: 0.0
material_offsety: 0.0
material_centerx: .5
material_centery: .5
material_rotation: 0.0
material_volume: 1

offset_audio: false
offset_limit: false
offset_sync: true
offset_mode: 'off'
offset_x: 0
offset_x_oscillate: 'off'
offset_y: 0
offset_y_oscillate: 'off'
offset_z: 0
offset_z_oscillate: 'off'

rhythm: 'half'
shape_delay: 'off'
shape_rhythm: 'nochange'
osci1_period: 2.0
osci1_amp: 0.6
osci2_period: 1.25
osci2_amp: 0.3
osci3_period: 0.66
osci3_amp: 0.1

pattern: matrix
pattern_padding: 1.0
pattern_paddingx: 1.0
pattern_paddingy: 1.0
pattern_paddingz: 1.0
pattern_centerx: 0
pattern_centery: 0
pattern_centerz: 0
pattern_audio: false
pattern_limit: false
pattern_padding_oscillate: 'off'
pattern_shapes: 112
pattern_sync: true
pattern_mover: 'off'
pattern_overlay: 'off'
pattern_overlay_volume: 0.0
pattern_overlay_volume_oscillate: 'off'

shape_geometry: tile
shape_sizedivider: 14
shape_moda: 0
shape_modb: 0
shape_modc: 0
shape_limit: false
shape_sync: true
shape_vertices: ''
shape_transform: 'off'
shape_transform_volume: 1
shape_modifier: 'off'
shape_modifier_volume: 1
shape_pairing: 'off'

sizing_mode: 'off'
sizing_scale: 1
sizing_scale_oscillate: 'off'
sizing_x: 1
sizing_y: 1
sizing_z: 1
sizing_x_oscillate: 'off'
sizing_y_oscillate: 'off'
sizing_z_oscillate: 'off'
sizing_audio: false
sizing_limit: false
sizing_sync: true
sizing_flip: 'off'

layer_transvisible: false
layer_positionx: 0
layer_positionx_oscillate: 'off'
layer_positiony: 0
layer_positiony_oscillate: 'off'
layer_positionz: 0
layer_positionz_oscillate: 'off'
layer_rotationx_oscillate: 'off'
layer_rotationy_oscillate: 'off'
layer_rotationz_oscillate: 'off'
layer_rotationx: 0
layer_rotationy: 0
layer_rotationz: 0

lighting_type: 'off'
lighting_fog: false
lighting_fog_near: 1500
lighting_fog_far: 2000
lighting_ambient: false
lighting_ambient_intensity: 1
lighting_bottom: false
lighting_color: '#fff'
lighting_intensity: 1
lighting_pattern: 'ring'
lighting_pattern_lights: 1
lighting_pattern_rotation: 0
lighting_pattern_rotation_oscillate: 'off'
lighting_pattern_padding: 1
lighting_pattern_padding_oscillate: 'off'
lighting_pattern_paddingx: 1
lighting_pattern_paddingy: 1
lighting_pattern_paddingz: 1
lighting_pattern_centerx: 0
lighting_pattern_centerx_oscillate: 'off'
lighting_pattern_centery: 0
lighting_pattern_centery_oscillate: 'off'
lighting_pattern_centerz: 1
lighting_pattern_centerz_oscillate: 'off'
lighting_lookat: 'center'
lighting_lookat_centerx: 0
lighting_lookat_centerx_oscillate: 'off'
lighting_lookat_centery: 0
lighting_lookat_centery_oscillate: 'off'
lighting_lookat_centerz: -1
lighting_lookat_centerz_oscillate: 'off'

lighting_angle: 1.05
lighting_penumbra: 1
lighting_intensity_oscillate: 'off'
lighting_angle_oscillate: 'off'
lighting_penumbra_oscillate: 'off'
lighting_shadows: false

background_mode: 'transparent'
background_color: '#000000'
background_input: 'none'
background_volume: 1
#background_mapping: todo background_mapping
background_wraps: ClampToEdgeWrapping
background_wrapt: ClampToEdgeWrapping
background_repeatx: 1.0
background_repeaty: 1.0
background_offsetx: 0.0
background_offsety: 0.0
background_centerx: .5
background_centery: .5
background_rotation: 0.0
background_volume_oscillate: 'off'

shape_lookat: 'off'
shape_lookat_centerx: 0.0
shape_lookat_centerx_oscillate: 'off'
shape_lookat_centery: 0.0
shape_lookat_centery_oscillate: 'off'
shape_lookat_centerz: 0.0
shape_lookat_centerz_oscillate: 'off'
pattern_rotation: 'off'
locking_shapex: false
locking_shapey: false
locking_shapez: false
pattern_rotation_multiplier: 1
locking_shapex_multiplier: 1
locking_shapey_multiplier: 1
locking_shapez_multiplier: 1

rotation_mode: 'default'
rotation_x: false
rotation_x_random: false
rotation_x_volume: 1.0
rotation_y: false
rotation_y_random: false
rotation_y_volume: 1.0
rotation_z: false
rotation_z_random: false
rotation_z_volume: 1.0
rotation_sync: true
rotation_direction: 'random'
rotation_easing: 'off'

rotation_offset_mode: 'off'
rotation_offsetx: 0.0
rotation_offsetx_oscillate: 'off'
rotation_offsety: 0.0
rotation_offsety_oscillate: 'off'
rotation_offsetz: 0.0
rotation_offsetz_oscillate: 'off'

shaders: {}