session: 'root'
play: true
reset: false
debug: false
monitor: false
push_layers: false
push_sources: false
shuffleable: ''
shuffle_mode: 'off'
shuffle_every: 16
tempo: 120.00
beat: true
peak_bpm_detect: true
audio: 'off'
volume: 1.00
filter_type: 'off'
filter_frequency: 350
layer: 0
peak_threshold_end: 3.6