
display_mask_shape:
  off: off
  triangle: triangle
  rect: rect
  quad: quad
  pentagon: pentagon
  hexagon: hexagon
  octagon: octagon
  decagon: decagon
  dodecagon: dodecagon
  hectagon: hectagon
  icosagon: icosagon

display:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13

video: {}

display_speed: &speeds
  peak: peak
  full: fulls
  half: halfs
  quarter: quarters
  eight: eights

border_speed:
  *speeds