group0: ''
group1: ''

sequence0_input: 'off'
sequence1_input: 'off'
sequence2_input: 'off'
sequence3_input: 'off'
sequence4_input: 'off'

sequence0_overlay: 'off'
sequence1_overlay: 'off'
sequence2_overlay: 'off'
sequence3_overlay: 'off'
sequence4_overlay: 'off'

sequence0_jump: false
sequence1_jump: false
sequence2_jump: false
sequence3_jump: false
sequence4_jump: false

sequence0_audio: false
sequence1_audio: false
sequence2_audio: false
sequence3_audio: false
sequence4_audio: false

sequence0_reversed: false
sequence1_reversed: false
sequence2_reversed: false
sequence3_reversed: false
sequence4_reversed: false

sequence0_speedup: false
sequence1_speedup: false
sequence2_speedup: false
sequence3_speedup: false
sequence4_speedup: false

sequence0_speeddown: false
sequence1_speeddown: false
sequence2_speeddown: false
sequence3_speeddown: false
sequence4_speeddown: false

sequence0_flipx: false
sequence1_flipx: false
sequence2_flipx: false
sequence3_flipx: false
sequence4_flipx: false

sequence0_flipy: false
sequence1_flipy: false
sequence2_flipy: false
sequence3_flipy: false
sequence4_flipy: false

sequence0_flipa: false
sequence1_flipa: false
sequence2_flipa: false
sequence3_flipa: false
sequence4_flipa: false

sequence0_passthrough: false
sequence1_passthrough: false
sequence2_passthrough: false
sequence3_passthrough: false
sequence4_passthrough: false

sequence0_speed: 1.0
sequence1_speed: 1.0
sequence2_speed: 1.0
sequence3_speed: 1.0
sequence4_speed: 1.0

sequence0_brightness: 1.0
sequence1_brightness: 1.0
sequence2_brightness: 1.0
sequence3_brightness: 1.0
sequence4_brightness: 1.0

sequence0_osci: 'off'
sequence1_osci: 'off'
sequence2_osci: 'off'
sequence3_osci: 'off'
sequence4_osci: 'off'

sequence0_blendmode: '0'
sequence1_blendmode: '0'
sequence2_blendmode: '0'
sequence3_blendmode: '0'
sequence4_blendmode: '0'

sequence0_start: 0
sequence1_start: 0
sequence2_start: 0
sequence3_start: 0
sequence4_start: 0

sequence0_end: 0
sequence1_end: 0
sequence2_end: 0
sequence3_end: 0
sequence4_end: 0

sample0_enabled: false
sample1_enabled: false
sample2_enabled: false
sample3_enabled: false
sample4_enabled: false
sample5_enabled: false

sample0_record: false
sample1_record: false
sample2_record: false
sample3_record: false
sample4_record: false
sample5_record: false

sample0_beats: 4
sample1_beats: 4
sample2_beats: 4
sample3_beats: 4
sample4_beats: 4
sample5_beats: 8

sample0_store: false
sample1_store: false
sample2_store: false
sample3_store: false
sample4_store: false
sample5_store: false

sample0_load: false
sample1_load: false
sample2_load: false
sample3_load: false
sample4_load: false
sample5_load: false

display_source: 'animation'
display_sequence: 0
material_map: none

lighting_type: 'off'
lighting_color: 'current'
lighting_brightness: 1.0
lighting_speed: 'eight'
lighting_pattern_lights: 1
lighting_scale: 1